### ISSUE TITLE
They've surrounded us! These blasted pop up walls!

### ISSUE THREAD

**Issue by TapGhoul** [ValveSoftware/portal2#116]
During sp_a1_wakeup, if you look away from glados (the opposite direction) after wheatley has flipped all the switches, a half-circle wall will appear out of nowhere, and block the back part of the view.

http://steamcommunity.com/sharedfiles/filedetails/?id=233325561
![2014-03-01_00005](https://f.cloud.github.com/assets/3120639/2301002/94a2dca8-a11c-11e3-8950-a0e0078332d8.jpg)

http://steamcommunity.com/sharedfiles/filedetails/?id=233325596
![2014-03-01_00006](https://f.cloud.github.com/assets/3120639/2301004/98700f7c-a11c-11e3-91f1-1e1615ed1aff.jpg)

I am using linux.

**Comment by timjp87** [comment]
This is normal. In this scene the developers don't want the player to get out and run around, since it is used to tell the story via an ingame cutscene. Otherwise you could run to the other side of the room and GlaDOS would be talking to the hole in the ground. So they put walls there instead of only invisible walls which would make the player confused as to why he can't get out.

**Comment by TapGhoul** [comment]
I thought they used to just be invisible, and it was just that you couldn't get out of that hole, at least how they tried to make it look. But fair enough, except for the fact that it appears out of nowhere. You actually need to move your view quite a bit further along for them to appear. But ok.
