### ISSUE TITLE
Buggy portal init script

### ISSUE THREAD

**Issue by rmsrepliedtomeonce** [ValveSoftware/portal2#119]
Error: bash: ./portal2.sh: /bin/bash^M: bad interpreter: No such file or directory
Cause: Unknown
Replicateable: Always
Relevant system info:
Debian GNU/Linux (running linux 3.12.1) with systemd 204 and the fglrx non-free drivers
/bin/sh is a symlink to /bin/dash

**Comment by iiv3** [comment]
This is fixed in the "Portal 2 (beta) [beta]". You have to enable it in: right_click->Properties->Betas, change the "Select the beta you would like to opt into" from "None" to "beta - Beta".

I guess you found the solution on your own, since you closed the bug. :)
But it is good to have it written anyway.
