### ISSUE TITLE
Lift at end of "The Reunion" rotates the wrong way.

### ISSUE THREAD

**Issue by alebahn** [ValveSoftware/portal2#135]
I don't have any screen shots because I wasn't sure at first and I don't a save since I'm playing with developer commentary on.
The last lift to take you out of the condemned track into modern aperture proper has the top part and bottom part of the lift rotating opposite directions. I looked up a let's play to ensure this isn't in the windows version.
Because the top and bottom are rotating opposite directions, the cables that are supposed to connect the top and bottom look twisted together.

Steam system information:
https://gist.github.com/alebahn/9311707

**Comment by Arbitrary007** [comment]
I thought I saw a report much like this before, but I can't seem to find it in closed or open issues, so I'll add my "I am experiencing this, too" here. It's the part right after the three alpha, beta, and gamma tubes get hooked up to the upper levels when the lift comes down. You can spot the issue just watching the lift as it comes down since the cables all seem to converge between the top and bottom part of the lift. If looking up while on the lift, you can see the effect. Quite interesting to watch.

**Comment by alebahn** [comment]
@Arbitrary007 You're right. I just found this issue is a duplicate of #76 .
