### ISSUE TITLE
Portal 2 crashes graphics stack [Arch linux 64]

### ISSUE THREAD

**Issue by josefnpat** [ValveSoftware/portal2#164]
I am running the latest nVidia blob on arch linux 64

```
extra/nvidia 334.21-2 [installed]
    NVIDIA drivers for linux
```

After about 10-15 minutes of playing portal 2, it crashes my graphics stack forcing me to reboot.

It turns off my monitors and then loops the last second of audio being played.

What logs can I post to help find the issue?

**Comment by timjp87** [comment]
Are you still able to "Ctrl+Alt+Fx" to a different tty? If you can, run "dmesg" and see if there are any NVRAM: Xid Kernel messages.

In my playthrough the game only froze on me once. Happend out of nowhere. I was able to switch to a different tty and htop showed on thread maxing out at 100% CPU load. I managed to kill the portal2 process, so it was probably a different issue than yours. I'm also on Arch Linux with the latest nvidia driver. If your PC locks up so that nothing but hitting reset works it will probably be a driver issue, therefore looking for NVRAM kernel messages is a good idea.

You could install openssh and start the sshd service and log into your PC from a different PC/Smartphone/Tablet and run "journalctl -kf" to let it follow the kernel messages or "journalctl -f" to follow all messages.

Make sure you are in the systemd-journal group so you can see all the logs.

**Comment by josefnpat** [comment]
I am not able to switch to a different tty. This issue seems to have cropped up in one of the updates within the past few weeks.

I will log my dmesg and journalctl to disk and try to reproduce the error.

**Comment by josefnpat** [comment]
I was able to reproduce it, and ssh'd in, and got the journalctl and the dmesg.

```
Mar 14 20:46:43 seppi7 kernel: NVRM: GPU at 0000:02:00.0 has fallen off the bus.
Mar 14 20:46:43 seppi7 kernel: NVRM: os_pci_init_handle: invalid context!
Mar 14 20:46:43 seppi7 kernel: NVRM: os_pci_init_handle: invalid context!
Mar 14 20:46:43 seppi7 kernel: NVRM: GPU at 0000:02:00.0 has fallen off the bus.
Mar 14 20:46:43 seppi7 kernel: NVRM: os_pci_init_handle: invalid context!
Mar 14 20:46:43 seppi7 kernel: NVRM: os_pci_init_handle: invalid context!
```

I found this is also happening when I play SC2 in wine, which makes me think that this is driver related as well.

Unless you have any advice, feel free to mark this issue as invalid.

Thanks for your time!

**Comment by timjp87** [comment]
I would say create a bug report here:
https://devtalk.nvidia.com/default/board/98/linux/

Reproduce the bug and run "nvidia-bug-report.sh" as root from ssh. It will create a bug-report.tar.gz file in your current working directory with your complete dmesg.log etc. which you can attach to your thread. The nvidia-bug-report.sh is installed as part of nvidia-utils so you can launch it from anywhere.

**Comment by timjp87** [comment]
Apparently cleaning the PCIe connector fixes this in some cases.

https://bbs.archlinux.org/viewtopic.php?id=168980

**Comment by josefnpat** [comment]
This issue no longer occurs. Updating seems to have fixed the issues; I suspect the nvidia blobs.
