### ISSUE TITLE
OS X [not linux specific]: missing sounds

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/portal2#195]
In the current beta, many sounds are not played, notably dialogs. 
OS X 10.9.2, 2006 Mac Pro without specific sound hardware.

**Comment by Tele42** [comment]
Have you been in the beta branch since the linux port got added? Linux had an initial port issue just like this due to a case-sensitive library name mis-match. Per https://github.com/ValveSoftware/portal2/issues/5#issuecomment-36083539 please check if something similar has affected your game install.

**Comment by jeanlain** [comment]
I reinstalled the game and the issue is still there. I don't have "libmiles.so" in my portal 2 bin directory but I have "libmilesmachox86.dylib". Renaming it "libMilesmachox86.dylib" had no effect.

**Comment by jeanlain** [comment]
This appears to be fixed now (OS X 10.9.3).
