### ISSUE TITLE
Portal 2 should let you pick a lower resolution than the window size in fullscreen mode

### ISSUE THREAD

**Issue by Plagman** [ValveSoftware/portal2#2]
Eg. select 1280x720 resolution when fullscreen on a 1920x1080 display and upscale the rendering.

**Comment by ghost** [comment]
I tried setting 1280x720 resolution on my 1920x1080 display and it didn't apply. I guess that's the same bug.

**Comment by mattyy1hp** [comment]
I have the same problem. My native resolution is 1920x1080 and I can't change it.

Debian Sid 64bit, Linux 3.13-1, Geforce GT 630M (331.38 drivers).

**Comment by linardv** [comment]
Until this issue is resolved, people who want to change their resolution could try the following workaround:
1. Go to your Library
2. Right click on "Portal 2 (Beta) [beta]" and select "Properties"
3. In the "General" tab, click on the button "Set launch options..."
4. Indicate to launch the game in windowed mode (-sw) and specify the preferred resolution option you had in-game (e.g. 720x480, 1280x800, ... for 16:10 displays, other values for other aspect ratios). For example:
`-sw -width 720 -height 480`

For more information about these launch options see: [Steam - Setting Game Launch Options](https://support.steampowered.com/kb_article.php?ref=1040-JWMT-2947)

**Comment by davidw-valve** [comment]
This has now been fixed.
