### ISSUE TITLE
sound stuck in a loop after playing the game for about an hour

### ISSUE THREAD

**Issue by majewsky** [ValveSoftware/portal2#261]
This bug seems to have been introduced only recently (maybe with the Steam Controller update of 2015-10-10), since I have only observed it the last three days.

After I have been playing for something over an hour, the audio suddenly gets stuck in a loop of maybe 100-200 ms, so no audio or dialogue can be heard anymore. When I make it through the level and the next level loads, the sound loop stops, but after that, I'm getting no sound whatsoever. The only workaround I found is to restart the game.

System Information: https://gist.github.com/majewsky/be6fa691ed7644a1f5c5

**Comment by Stewmath** [comment]
I seem to have the same issue, on a similar system (arch linux). Only occurred after about an hour of gameplay.

Dunno if it's relevant, but I turned off multicore rendering because that was causing outright crashes. When enabled, it would cause the same audio loop after only seconds of gameplay, the difference being that the rest of the game stopped functioning as well.

System information: https://gist.github.com/Drenn1/f6b32d5ea3f05f168cf4

**Comment by J4nsen** [comment]
I have the same problem on two linux machines (#1 Ubuntu 14.04 x64, #2 Kubuntu 15.10). Happens after about an hour of playing.

System Info of #2 machine: https://gist.github.com/J4nsen/2bda91feeb87d8f2cc74

**Comment by timjp87** [comment]
I have the same issue. 
https://gist.github.com/timjp87/6a7ce96e324baf52cf7b 

No idea what triggers this.

**Comment by davidw-valve** [comment]
This should be fixed now in an update that was just released.
