### ISSUE TITLE
Crash when loading a map/save

### ISSUE THREAD

**Issue by Turmfalke2** [ValveSoftware/portal2#313]
hi,
The game crashes in libc every time I try to load a save game or start a new run.

`traps: portal2_linux[2816] general protection fault ip:f7dc096a sp:ffdb5d58 error:0 in libc-2.30.so[f7d11000+161000]`

assert_20191216204621_34.dmp and crash_20191216204632_1.dmp were uploaded, the crash was discarded and the assert dump recorded as bp-06f4a351-433f-4509-9fcf-310252191216

System information:  
https://gist.github.com/Turmfalke2/249954d28cfb355e761390837ab78d33

**Comment by rym002** [comment]
compile glibc with -mstackrealign

**Comment by Turmfalke2** [comment]
Thank you. I can confirm that recompiling glibc with mstackrealign works. How did you figure this out? Is there anyway I can see what stack alignment a program expects?

**Comment by rym002** [comment]
https://wiki.gentoo.org/wiki/Steam/Games_troubleshooting#Half-Life_2

**Comment by tomaszg7** [comment]
Thanks for the tip. I was struggling with the issue myself as well. Surprisingly, only my newer machines with Zen processors were affected (Ryzen 3600 and Athlon 200GE + AMDGPU), while older one with pre-Zen AMD processor (Athlon X4 750K + RADEON) was working fine. However instead of rebuilding a critical system component with non-default options I just run Portal via Proton. Not an optimal solution, but the best I could find.

**Comment by tomaszg7** [comment]
Seems the bug is fixed by today's update.

**Comment by kisak-valve** [comment]
Closing per the last comment.
