### ISSUE TITLE
Can't Upload Any More Test Chambers (???)

### ISSUE THREAD

**Issue by ADAMMMMMMMMMMMMMMMMMMMMMMMMMMM** [ValveSoftware/portal2#386]
I've had this issue for a while now, and I've tried multiple things, but I'm just absolutely stumped. Please help me...
Tried to upload a new test chamber, relatively normal sized, and when I hit "Publish", I got this error message

![Screenshot (12)](https://user-images.githubusercontent.com/102838245/191625810-1ee1a97b-0f4f-4bac-b7e6-f977b60c6219.png)

I have no idea what's going on. Obviously, it's something with the Steam Cloud or something like that, but I'm not entirely sure.
Please respond with help as soon as possible, that'd be very much appreciated

**Comment by ADAMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
Forgot to mention, probably important info, but I do have a modded version of the test chamber editor. Figured that might be important

**Comment by vrad-exe** [comment]
Have you actually read the error message? You don't have enough space in your Steam Cloud to upload the map, you only have 42 megabytes free, but BEEmod maps are usually bigger than that (because of packed custom resources). You'll probably need to delete other files (other maps, screenshots, etc.) to make room.

**Comment by ADAMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
The problem has since been fixed, but thank you for the additional
information!
