### ISSUE TITLE
Portal 2 won't start and repeatedly redownloads

### ISSUE THREAD

**Issue by MichaelBlume** [ValveSoftware/portal2#71]
When I click play, it looks like it's about to launch for a moment and nothing happens. If I click through to verify integrity of game files, it tells me ~3000 files are wrong and will be redownloaded, and proceeds to download 6GB of data. This has happened thrice, so I don't _think_ it's some matter of, I don't know, transport corruption.

**Comment by davidw-valve** [comment]
Have you had this happen with any other games?

Have you tried just explicitly deleting Portal2 and re-downloading from scratch?

Have you opted in to the Beta as instructed in the readme?

**Comment by bespokebob** [comment]
Make sure you opt in to the beta in the game properties -> Betas.

**Comment by csallen1204** [comment]
Same issue here. 

Ran the installer from the command line and saw this:

/bin/sh: 1: /home/<user>/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: not found

There needs to be quotes around "Portal 2" otherwise the filepath is invalid. I couldn't find which script that is defining the filepath this way.

**Comment by davidw-valve** [comment]
Opt in to the beta as described on the readme here and it will work: https://github.com/ValveSoftware/portal2
