### ISSUE TITLE
/bin/bash^M

### ISSUE THREAD

**Issue by drmad** [ValveSoftware/portal2#77]
Hi.

I just downloaded it, but it doesn't run. In the logs there is this line:

/bin/sh: 1: /home/drmad/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: not found

Running the file directly from Bash, there is an Enter character before the LF:

bash: ./portal2.sh: /bin/bash^M: intérprete erróneo: No existe el archivo o el directorio

Removing that extra byte, a new error arises:

ERROR: ld.so: object '/home/drmad/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

I've check, the file doesn't exists.

I'm using Xubuntu Linux 13.10 64 bits, with Steam built on Feb 25 2014 13:46:32, API v013.

**Comment by ScottyBauer** [comment]
EDIT:

Turns out I hadn't opted into the beta and was thus missing the shared library. OP should confirm he has opted in by right clicking on portal 2(beta) -> Properties -> beta

# 

I can confirm on ubuntu 12.10
3.5.0-45-generic #68-Ubuntu SMP Mon Dec 2 21:58:52 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Game update: AppID 620 "Portal 2 (Beta)", ProcID 4828, IP 0.0.0.0:0
ERROR: ld.so: object '/home/sarah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/bin/sh: 1: /home/sarah/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: not found
CGameStreamThread: Added instance ID 4828 for appid 620
CGameStreamThread: Set render instance ID 4828 for appid 620

I checked the directory, and confirm that portal2.sh exists 

:~/.local/share/Steam/SteamApps/common/Portal 2$ ls -la | grep portal2.sh
-rwxrwxr-x  1 sarah sarah   1131 Feb 26 21:04 portal2.sh

After removing the ^M and attempting to launch from steam again:

RROR: ld.so: object '/home/sarah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
CGameStreamThread: Added instance ID 5288 for appid 620
/home/sarah/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: line 40: /home/sarah/.local/share/Steam/SteamApps/common/Portal 2/: Is a directory
pid 5292 != 5289, skipping destruction (fork without exec?)

I added some debug statements and the GAMEEXE var is never being set

**Comment by jarro2783** [comment]
Did you set the game to the beta in the game properties?

**Comment by davidw-valve** [comment]
Opt into the beta as detailed in the readme and it will work.
